title: "Cheatsheet docs"
description: "Dokumentacje dla Studentów Creative Coding"

# Just the Docs jako zdalny motyw (działa dobrze z GitHub Pages)
remote_theme: pmarsceill/just-the-docs

nav_enabled: true
search_enabled: true

# tutaj ustawiamy baseurl – patrz punkt 3 niżej
baseurl: "/creative_coding"

